# Generated by Django 2.2.4 on 2020-09-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
