# Generated by Django 2.2.4 on 2020-09-16 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200916_0623'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
